import Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :efl, Efl.Endpoint,
  #http: [port: {:system, "PORT"}],
  #url: [host: "example.com", port: 80],
  http: [port: 4000],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

# Configure logging for production
config :logger,
  backends: [:console, {Efl.LoggerBackend, :info_log}]

config :logger, :console,
  format: "$time $date $metadata[$level] $message\n",
  metadata: [:request_id]

config :logger, :info_log,
  level: :info

# Configure your database
config :efl, Efl.Repo,
  adapter: Ecto.Adapters.MyXQL,
  username: "root",
  password: "password",
  database: "classification_utility_dev",
  hostname: "mysql",
  pool_size: 20,
  charset: "utf8mb4",
  collation: "utf8mb4_unicode_ci"
# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :classification_utility, Efl.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :classification_utility, Efl.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :classification_utility, Efl.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
import_config "mailgun.exs"
import_config "proxy_rotator.exs"
